version: '3'


volumes:

  postgresdata:
  redisdata:
  esdata:
    driver: local
  esdataaux:
    driver: local


networks:

  app-network:


services:

  web:
    container_name: web
    build: .
    image: waggle_web
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 project.wsgi --workers=2 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "35729:35729"
    depends_on:
      - pg
      - rd
      - es
      - esaux
    networks:
      - app-network

  pg:
    # Run psql postgres postgres, then \password <new-password>, then \q to change default password
    # Run CREATE DATABASE <dbname> ENCODING 'UTF8'; to create new database if not using default "postgres"
    image: postgres:9.6
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    networks:
      - app-network

  adminer: # Database Web Viewer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pg
    networks:
      - app-network

  rd:
    image: "redis:5.0"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  ngx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - web

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  esaux:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdataaux:/usr/share/elasticsearch/data
    networks:
      - app-network
